#common properties
<<<<<<< HEAD
baseURL=https://www.saucedemo.com/

# Browser and URL
browser=chrome

# Test Credentials
username=standard_user
password=secret_sauce

#=======
>>>>>>> main


#Products name 
FirstProductName=Sauce Labs Backpack
SecondProductName=Sauce Labs Bike Light


#fields
firstName = Viraj
lastName = Sodaye
postalCode = 400087