# common properties
baseURL=https://www.saucedemo.com/

browser=chrome

username=standard_user
password=secret_sauce

FirstProductName=Sauce Labs Backpack
SecondProductName=Sauce Labs Bike Light

firstName=Viraj
lastName=Sodaye
postalCode=400087
