# common properties
baseURL=https://www.saucedemo.com/

browser=chrome

# test credentials
username=standard_user
password=secret_sauce

# product names (reference)
FirstProductName=Sauce Labs Backpack
SecondProductName=Sauce Labs Bike Light

# checkout fields
firstName=Viraj
lastName=Sodaye
postalCode=400087
